"""creating a table to store company details

Revision ID: aa248bf3cee7
Revises: b27fb6059995
Create Date: 2024-09-04 02:14:51.896038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa248bf3cee7'
down_revision = 'b27fb6059995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sr_no', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('year_founded', sa.Integer(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('size_range', sa.String(length=50), nullable=True),
    sa.Column('locality', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('linkedin_url', sa.String(length=200), nullable=True),
    sa.Column('current_employee', sa.Integer(), nullable=True),
    sa.Column('total_employee', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    # ### end Alembic commands ###
